### ISSUE TITLE
No headerbar gradient

### ISSUE THREAD

**Issue by mikeymop** [cassidyjames/ephemeral#124] opened 2019-03-20 05:30 UTC
I built version 4.2.0 on Fedora 29. I noticed that the headerbar does not have a gradient and instead appears in elementary dark.

Is there something that I have to do that is specific to elementary in order to have the Firefox Focus style headerbar on ephemeral?

**Comment by cassidyjames** [comment] 2019-03-20 14:06
@mikeymop Ephemeral checks if it's running on elementary OS, because even if the current stylesheet is named "elementary," there's no way to guarantee it supports the stylesheet constants I'm using. On elementary OS, I can presume that it's running an up-to-date compatible version.

https://github.com/cassidyjames/ephemeral/blob/3b119d030b53ede6fbc9e1424cd40f7c86862933/src/Application.vala#L112-L140

I'm inclined to close this because it's working as intended, but there's the check if you wanted to disable it locally.

**Closed by cassidyjames** 2019-03-20 14:06 UTC

**Comment by cassidyjames** [comment] 2019-03-20 14:08
@mikeymop actually instead of making `native ()` return true, you'd probably want to modify this to remove the `native ()` check:

https://github.com/cassidyjames/ephemeral/blob/3b119d030b53ede6fbc9e1424cd40f7c86862933/src/Application.vala#L85-L93

**Comment by cassidyjames** [comment] 2020-03-28 18:45
@mikeymop if you're still interested, more recent versions of Ephemeral have separated out the concepts of "native" and "elementary stylesheet". I apply the elementary styling if you're using an elementary stylesheet, regardless of whether it's running on elementary OS. Hopefully this helps!

https://github.com/cassidyjames/ephemeral/blob/5be06875e9f9792ea1ae5ae27c2873a7103be177/src/Application.vala#L124-L155

https://github.com/cassidyjames/ephemeral/blob/5be06875e9f9792ea1ae5ae27c2873a7103be177/src/Application.vala#L82-L92

**Comment by mikeymop** [comment] 2020-03-29 17:09
Thank you! 

I have been very satisfied with bypassing the checks and compiling on my own.

I've since switched from Pantheon to Gnome 3.36, and elementary.css, so this change will save me the self maintenance.
