### ISSUE TITLE
Allow open websites without https://

### ISSUE THREAD

**Issue by asakura42** [cassidyjames/ephemeral#282] opened 2021-05-07 04:45 UTC
When I try to open website from commandline without https (for example `com.github.cassidyjames.ephemeral duckduckgo.com`) I get "Whoops" page and browser points to `file:///home/asakura/duckduckgo.com` instead of `https://duckduckgo.com`

**Comment by cassidyjames** [comment] 2022-01-06 18:32
Thanks for filing this! It's actually a duplicate of #113

**Closed by cassidyjames** 2022-01-06 18:32 UTC
